### ISSUE TITLE
PreferenceFragment error

### ISSUE THREAD

**Issue by imminent** [Prototik/HoloEverywhere#165]
I get `Binary XML file line #2: Error inflating class com.WazaBe.HoloEverywhere.preference.PreferenceScreen` in the HoloEverywhere `PreferenceFragment` and my preferences.xml looks like

``` xml
<PreferenceScreen xmlns:holo="http://schemas.android.com/apk/res-auto">
</PreferenceScreen>
```

is this a 1.3 issue? because I'm waiting for the maven repository to be updated.

Here's my preference activity, since it's pretty simple

``` java
import android.os.Bundle;

import com.WazaBe.HoloEverywhere.preference.PreferenceFragment;
import com.WazaBe.HoloEverywhere.preference.PreferenceManager;
import com.WazaBe.HoloEverywhere.preference.SharedPreferences;
import com.WazaBe.HoloEverywhere.sherlock.SActivity;

/**
 * @author Dandré Allison
 */
public class SettingsActivity extends SActivity
        implements SharedPreferences.OnSharedPreferenceChangeListener {

    public static class SettingsFragment extends PreferenceFragment {
        @Override
        public void onCreate(Bundle icicle) {
            super.onCreate(icicle);

            // Loads the XML preference file
            addPreferencesFromResource(R.xml.preferences);
        }
    }

    @Override
    protected void onCreate(Bundle icicle) {
        super.onCreate(icicle);

        // Displays the fragment as the main content.
        getSupportFragmentManager().beginTransaction()
                .replace(android.R.id.content, new SettingsFragment())
                .commit();
    }


    @Override
    protected void onResume() {
        super.onResume();

        // Registers a listener for setting changes
        PreferenceManager.getDefaultSharedPreferences(this).registerOnSharedPreferenceChangeListener(this);
    }

    @Override
    protected void onPause() {
        super.onPause();

        // Unregisters the listener set in onResume()
        PreferenceManager.getDefaultSharedPreferences(this).unregisterOnSharedPreferenceChangeListener(this);
    }

    @Override
    public void onSharedPreferenceChanged(SharedPreferences preferences, String key) {

    }
}
```

**Comment by Prototik** [comment]
Use only one: PreferenceFragment with (S)Activity or SPreferenceActivity.

**Comment by imminent** [comment]
I'm using SActivity aren't I? It only has one fragment.

**Comment by Prototik** [comment]
Ops, yes, i'm sorry. Well, print stacktrace. Demo use SActivity and SPreferenceFragment, everything okay.

**Comment by imminent** [comment]
Yeah I was following the demo when I wrote my class. I'm getting something
about generic not finding the init method that takes the context and the
activity I believe. I can post the log later.

**Comment by imminent** [comment]
``` log
ERROR/AndroidRuntime(1787): FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bumday/com.bumday.ui.SettingsActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class com.WazaBe.HoloEverywhere.preference.PreferenceScreen
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
        at android.app.ActivityThread.access$600(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.WazaBe.HoloEverywhere.preference.PreferenceScreen
        at com.WazaBe.HoloEverywhere.preference.GenericInflater.createItem(GenericInflater.java:79)
        at com.WazaBe.HoloEverywhere.preference.GenericInflater.onCreateItem(GenericInflater.java:199)
        at com.WazaBe.HoloEverywhere.preference.GenericInflater.createItemFromTag(GenericInflater.java:100)
        at com.WazaBe.HoloEverywhere.preference.GenericInflater.inflate(GenericInflater.java:173)
        at com.WazaBe.HoloEverywhere.preference.GenericInflater.inflate(GenericInflater.java:147)
        at com.WazaBe.HoloEverywhere.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:351)
        at com.WazaBe.HoloEverywhere.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:75)
        at com.bumday.ui.SettingsActivity$SettingsFragment.onCreate(SettingsActivity.java:23)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:834)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1080)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:622)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1416)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:505)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
        at android.app.Activity.performStart(Activity.java:5018)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032)
        ... 11 more
        Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
        at java.lang.Class.getConstructorOrMethod(Class.java:460)
        at java.lang.Class.getConstructor(Class.java:431)
        at com.WazaBe.HoloEverywhere.preference.GenericInflater.findConstructor(GenericInflater.java:125)
        at com.WazaBe.HoloEverywhere.preference.GenericInflater.createItem(GenericInflater.java:72)
        ... 26 more
```

**Comment by Prototik** [comment]
Constructor PreferenceScreen(Context, AttributeSet) declared, Moreover, it is only one.

**Comment by niko001** [comment]
I'm getting the same issue when changing the Demo-Project from a PreferenceFragment to a PreferenceActivity. Doesn't matter if I use PreferenceFragment with (S)Activity or SPreferenceActivity. If I delete everything but <PreferenceScreen xmlns:holo="http://schemas.android.com/apk/res-auto" > </PreferenceScreen> from  preferences.xml, it works, but as soon as I add a PreferenceCategory or any other Preference (e.g. EditTextPreference), it crashes.

11-05 15:05:19.939: E/AndroidRuntime(19899): FATAL EXCEPTION: main
11-05 15:05:19.939: E/AndroidRuntime(19899): android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.LayoutInflater.createView(LayoutInflater.java:613)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at com.WazaBe.HoloEverywhere.LayoutInflater.tryCreateView(LayoutInflater.java:258)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:210)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at com.WazaBe.HoloEverywhere.preference.Preference.onCreateView(Preference.java:515)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at com.WazaBe.HoloEverywhere.preference.Preference.getView(Preference.java:405)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at com.WazaBe.HoloEverywhere.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:159)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.AbsListView.obtainView(AbsListView.java:2267)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.ListView.makeAndAddView(ListView.java:1769)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.ListView.fillDown(ListView.java:672)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.ListView.fillFromTop(ListView.java:733)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.ListView.layoutChildren(ListView.java:1622)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.AbsListView.onLayout(AbsListView.java:2102)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.View.layout(View.java:13754)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.View.layout(View.java:13754)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.View.layout(View.java:13754)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.View.layout(View.java:13754)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.View.layout(View.java:13754)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.View.layout(View.java:13754)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.View.layout(View.java:13754)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.Choreographer.doFrame(Choreographer.java:525)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.os.Handler.handleCallback(Handler.java:615)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.os.Handler.dispatchMessage(Handler.java:92)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.os.Looper.loop(Looper.java:137)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.app.ActivityThread.main(ActivityThread.java:4745)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at java.lang.reflect.Method.invokeNative(Native Method)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at java.lang.reflect.Method.invoke(Method.java:511)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at dalvik.system.NativeStart.main(Native Method)
11-05 15:05:19.939: E/AndroidRuntime(19899): Caused by: java.lang.reflect.InvocationTargetException
11-05 15:05:19.939: E/AndroidRuntime(19899):    at java.lang.reflect.Constructor.constructNative(Native Method)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
11-05 15:05:19.939: E/AndroidRuntime(19899):    at android.view.LayoutInflater.createView(LayoutInflater.java:587)
11-05 15:05:19.939: E/AndroidRuntime(19899):    ... 56 more
11-05 15:05:19.939: E/AndroidRuntime(19899): Caused by: java.lang.UnsupportedOperationException: Can't convert

**Comment by niko001** [comment]
I fixed it by adding 

@Holo(forceThemeApply = true, layout = R.layout.content)

before the class definition
