### ISSUE TITLE
ShelockMapFragment / Acitivity

### ISSUE THREAD

**Issue by jcampbell05** [Prototik/HoloEverywhere#174]
How would I go about implementing a Map Fragment or activity for Sherlock using Holo Everywhere. It's a brilliant library but this is the only thing that is missing

**Comment by Prototik** [comment]
Feature request accepted :) tommorow.

**Comment by Prototik** [comment]
Or not tommorow... :)
Well, you mean MapActivity/MapFragment from Google Api with Google Maps?

**Comment by jcampbell05** [comment]
I'm using the Sherlock Version that uses it but Holo doesn't have either the MapActivity/MapFragment from Google Api with Google Maps or SherlockMapActivity/MapFragment from Sherlock Google Maps Plugin.

I would only need the sherlock version but I think both would be great :)

**Comment by ismoli** [comment]
Hi, I have just created a fork with quick implementation of SMapActivity which is derived from Google's MapActivity. I guess this is what you are looking for. 
https://github.com/ismoli/HoloEverywhere

**Comment by jcampbell05** [comment]
Thank You :)

**Comment by Matungos** [comment]
I would really appreciate this feature!

**Comment by Matungos** [comment]
ismoli,
will you update your fork (with MapActivity) to use HE 1.4?

**Comment by ismoli** [comment]
Matungos, not sure, I think it would be better to merge with main developers if they are ok with it.

**Comment by mdumrauf** [comment]
IMHO, I don't beleive it should be included in HoloEverywhere. It's out of scope. May be @JackeWharton could give us an opinion about it.

BTW, I think it should be wrapped from ActionBarSherlock rather than from HoloEverywhere, as it is a closer layer to the wrapper of android support library v4.

**Comment by jcampbell05** [comment]
Perhaps the Sherlock Functionality of the library could be made into a module you could include if you decide to use sherlock and will include the maps functionality (I'm not sure if Holoeverywhere supports even the original maps activity)

**Comment by mdumrauf** [comment]
HoloEverywhere by itself doesn't, but you can use https://github.com/JakeWharton/ActionBarSherlock-Plugin-Maps that  gives support to MapActivity.

The thing is that you can't use a MapView inside a Fragment because when it detaches the fragment's layout (e.g. changing among tabs) the MapView is leaked (remains attached to it's parent view). So when you try to attach the fragment again you get a runtimeexception related to only being able to have one MapView per MapActivity.

As a workaround, I kept the instance of the MapView inside the instance of the Fragment. When the onCreate() is called I saved the instance, and when the onCreateView() is called I made an addView() to the rootView. Then, in onDestroyView() y did removeView() of the MapView instance from it's parent.

**Comment by mdumrauf** [comment]
Good news. New maps api was released 4 days ago as part of Google Play Services v2. Therefore, extending from MapActivity is no longer needed to hold a MapView. You just have to extend from Activity as usual, and use the new MapFragment.

Given this, the issue may be closed if MapFragment is fully supported.

More info:
- http://android-developers.blogspot.com.br/2012/12/new-google-maps-android-api-now-part-of.html.
- https://developers.google.com/maps/documentation/android/start#getting_the_google_maps_android_api_v2

**Comment by jcampbell05** [comment]
:) Why didn't they do this in the first place haha :)
