### ISSUE TITLE
git submodule support

### ISSUE THREAD

**Issue by almozavr** [Prototik/HoloEverywhere#25]
Please, correct .gitignore (remove '/' before project.properties) and git rm project.properties to make library be used as a git submodule without a pain. Thanks!

**Comment by bartoszgadzala** [comment]
Hi Aleksey, can you explain why do You want to remove project.properties? In my opinion (which can be wrong - I'm not quite sure and that's why I'm asking) project.propeties should be fixed to something like this:

```
target=android-15
android.library=true
android.library.reference.1=../contrib/ActionBarSherlock/library
```

and then new submodule contrib/ActionBarSherlock should be added to HoloEverywhere. In that way, we don't have to modify project.properties to fix reference to ABS library and Eclipse will not complain about missing project.properties while importing the project.

I've already created a pull request (see  Issue #29), but then I've found Your issue report which forced me to think that I may be wrong.

**Comment by almozavr** [comment]
So, you propose to add ABS to your project, and it's not a bad idea, but what if:
1. User doesn't want to use ABS, only Holo theme;
2. User already has ABS somewhere in his project (maybe even modified version) and don't want duplicate libraries across project and workspace?

**Comment by bartoszgadzala** [comment]
Thanks for the response.
1. HoloEverywhere already depends on ABS (in Theme.HoloEverywhereDark.Sherlock for example) so it's not possible to don't use ABS right now. Maybe the real problem is a dependency on ABS and HoloEverywhere should be divided into
   a) pure HoloEverywhere without Theme.*.Sherlock, and
   b) HoloEverywhereABS with action bar stylings
   In that way user can use HoloEverywhere with or without ABS.

2.You are right, thanks for pointing that.

**Comment by mikepenz** [comment]
I'm not sure if ti's 100% related to this issue, but since you've pushed the update to the submodule i can't update my local repository anymore. I use sourcetree on my mac and it worked great until this update. It always mentions an issue with ActionbarSherlock. 

But why it wants to download ABS i've already an separate ActionbarSherlock repository on my harddrive?
