### ISSUE TITLE
cant add

### ISSUE THREAD

**Issue by mburumaxwell** [Prototik/HoloEverywhere#27]
When I add the library to my project, my project can no longer run. I get this error

[2012-06-18 07:53:30 - HoloDemoActivity] Conversion to Dalvik format failed with error 1

**Comment by ghost** [comment]
Can you check that you don't have two .JAR files that include the same package and classes in your build path, because that might causes the error 1. Try to solve this by cleaning the project -  Go to Project -> Clean -> Clean projects selected below -> select your project and click OK. Hope this works for you.

**Comment by mburumaxwell** [comment]
thanx. that fixed the problem
