### ISSUE TITLE
pom.xml error: Could not find artifact org.holoeverywhere:resbuilder:pom:1.4.3-SNAPSHOT

### ISSUE THREAD

**Issue by gosr** [Prototik/HoloEverywhere#292]
Here's what I did:

```
git clone https://github.com/ChristopheVersieux/HoloEverywhere.git
```

Then I get the newest version of HE.

In Eclipse, I add the library folder from HE as a project.

Eclipse gives me approx. 1 million errors (1238 to be precise). There are a bunch of "x cannot be resolved to a type".

But in pom.xml, the error mentioned in the title of this issue occurs.
I have absolutely no idea what should be done, and I'm sure that if the pom error is fixed, the rest of the errors will go away (because deleting the pom.xml fixes all errors, but the library won't work).

**Comment by Prototik** [comment]
Import resbuilder from root folder.

**Comment by gosr** [comment]
Sorry, please be more specific.
I know there is a folder called resbuilder, but how exactly should it be imported into Eclipse?

**Comment by Prototik** [comment]
File - import - exists project into workspace.

**Comment by gosr** [comment]
I did "General" -> "Existing Projects into Workspace".
Now I have "HoloEverywhere ResBuilder" in workspace.

Problem still occurs.

**Comment by Prototik** [comment]
Try to restart eclipse and again execute steps from Maven wiki page.

**Comment by gosr** [comment]
It's still not working.
I can't believe I'm the only one with this problem. Direct import from the github code into Eclipse, and then the error occurs.
Can you please try the steps I mentioned above? Preferably in a new workspace to avoid any old configurations etc.
That is, clone the github code, and add the library as an Eclipse project.

**Comment by Prototik** [comment]
Are you try to follow instructions on 'Maven' wiki page?

**Comment by stpn108** [comment]
I'm having the same issue but I can't find the right page on the Maven Wiki. Could you provide a link?

**Comment by e-nulien** [comment]
I am facing the same problem too and spent all afternoon trying to fix it ... no success.
Any idea or help would be appreciated. Thanks.

**Comment by shafty023** [comment]
I too am having the exact same issue and there doesn't seem to be any solution.

**Comment by shafty023** [comment]
Ever since this project switched to Maven it has been almost impossible to get working in Eclipse. Why would anyone want 6 library projects imported into Eclipse just to get HE working? I reverted back to my old pre-maven copy that only requires I import the library/ folder as a project and everything works. Is it not possible to get rid of the maven changes and go back to what used to work more simple?

**Comment by e-nulien** [comment]
Thanks for letting me know that I am not the only one having that problem. I gavto e up on it now. Importing Resbuilder and trying clean install didnt work either.
Could someone upload the last "non-maven" library so I can use it? Thanks.

**Comment by Gawdl3y** [comment]
I'm having the exact same issue, and nothing seems to fix it. I have followed the steps in the "Import into Eclipse" section of the Maven wiki page, and am still getting the same error.

**Comment by Hagith** [comment]
I'm new to Android evelopment and I wanted to try HoloEverywhere, but i'm facing the same issue for more than two hours now. I tried almost everything what i found in google, no success. Please help!

**Comment by Hagith** [comment]
OK. I didn't gave up and looks like I fixed this. Because I still don't understand how to manage dependencies with Maven, I'm not sure if I didn't broke something else :)
Now i have clean builds of all HE projects. Here you can see what I modified: https://github.com/rafalgalka/HoloEverywhere/compare/pr-pom-xml-error

After those changes I followed, step by step, instructions from maven wiki page.
Maybe this will help someone.

**Comment by Hagith** [comment]
Too good to be true... I added the HE library to my project and there's no build errors. When I want run it on my 2.3.6 test device error shows up in console:

[2013-03-01 01:16:47 - Dex Loader] Unable to execute dex: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
[2013-03-01 01:16:47 - AlterGo] Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

After some googling and updating android support library I have no idea how to fix it.

**Comment by thatseanfitz** [comment]
Why is this "closed" ? I have this problem and I don't see a real solution.

**Comment by kofi-de-com** [comment]
Could some one please look into this and reopen this issue. I have the same problem and following the steps on the Maven wiki page did not help. I always have these 3 errors remaining:

Description Resource    Path    Location    Type
Could not find artifact org.holoeverywhere:resbuilder:pom:1.4.3-SNAPSHOT    pom.xml /HoloEverywhere Demo    line 1  Maven pom Loading Problem
Could not find artifact org.holoeverywhere:resbuilder:pom:1.4.3-SNAPSHOT    pom.xml /HoloEverywhere Addon Preferences   line 1  Maven pom Loading Problem
Could not find artifact org.holoeverywhere:resbuilder:pom:1.4.3-SNAPSHOT    pom.xml /HoloEverywhere Library line 1  Maven pom Loading Problem

**Comment by kofi-de-com** [comment]
I found out that the problem is because the snapshots of version 1.4.3-SNAPSHOT are missing at https://oss.sonatype.org/content/repositories/snapshots

If you want to build the current HEAD and can not wait try these steps (worked for me):
- Follow the exact steps from the Maven wiki page under the section **# Import into Eclipse**
  (After that you should have only those 3 errors left that i mentioned in my previous post)

Then:
- Add `res` folder to add-on project roboguice
- Open the `pom.xml` of the project `HoloEverywhere Addons` and comment module roboguice (line 21)
  - I had to disable roboguice because it was causing such an error http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6302954

**EDIT:**
**Select `Run` - `Run configurations...`**
**Delete unnecessary configurations from `Android` section**
- Select section `Maven`, click `New launch configuration`, name it `HoloEverywhere ResBuilder Install`.
- Press `Browse Workspace...` button and select project with name `HoloEverywhere Resbuilder`
- Into `Goals` field type text: `clean install`
- Check `Skip tests`
- Click `Apply` - `Run`

**EDIT:**
**Select `Run` - `Run configurations...`**
- Select section `Maven`, click `New launch configuration`, name it `HoloEverywhere Build`.
- Press `Browse Workspace...` button and select project with name `HoloEverywhere`
- Into `Goals` field type text: `clean install`
- Check `Skip tests`
- Click `Apply` - `Run`
- Update the three projects with remaining errors as described in section **# Import into Eclipse**
  - `Right-click` - `Maven` - `Update project...`
  - `Right-click` - `Properties` - `Android` - add libraries as before

Wait until the workspace is finally build and you should be all set to use this library.

**Comment by thatseanfitz** [comment]
I followed you until the "select section Maven" part. I can't seem to find that anywhere. Perhaps I don't have Maven completely integrated with Eclipse?

**Comment by kofi-de-com** [comment]
Sorry I forgot to mention one step. I edited the post to be more clear.

If you can't find Maven under Run -> Run Configurations... make sure you have installed m2e (Maven Integration for Eclipse) and m2e-android (Android Configurator for M2E) from the Eclipse Marketplace
