### ISSUE TITLE
android:name attribute is missing

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#313]
I just updated HoloEverywhere to the latest version.
Unfortunately I'm now getting this exception:

```
Caused by: java.lang.IllegalStateException: Application instance isn't HoloEverywhere.
Put attr 'android:name="org.holoeverywhere.app.Application"' in <application> tag of AndroidManifest.xml
```

But why should I add an android:name attribute in my application tag?
I dont use this base class...

Thanks for your help!

**Comment by Prototik** [comment]
How is "why"? If it writes - believe me, it is so necessary. Or write this attribute in the manifest, or extend your own class from org.holoeverywhere.app.Application (like DemoApplication in demo project).

**Comment by imminent** [comment]
@zuecho The HoloEverywhere `Activity` class is programmed to throw that error when the `Application` class doesn't extend `org.holoeverywhere.app.Application`  (probably because it depends on the code in that class being executed to work properly). This means you can either implement an application class that extends that class, **OR** you can simply follow the recommendation and add '`android:name="org.holoeverywhere.app.Application"`' to your `<application>` tag in the AndroidManifest.xml. The problem is that the default Android framework `Application` doesn't execute the proper HoloEverywhere code to allow the HoloEverywhere `Activity` to work.

@Prototik maybe the error should say "or use a class that extends org.holoeverywhere.app.Application".
