### ISSUE TITLE
HoloEverywhere with Studio and Gradle

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#463]
If someone successfully compiled a HelloWorld project with HoloEverywhere in Studio with Gradle it would be great to add the steps to the usage section.
I've wasted all morning trying to do that without success.

**Comment by Prototik** [comment]
HoloEverywhere will migrate on gradle and official Studio support only since stable Studio release.

**Comment by Dahlgren** [comment]
Since existing maven repos contain apklibs instead of the new aar format which Gradle uses you'll have to compile and package ActionBarSherlock with gradle to a local repo. ActionBarSherlock already got a Gradle build file in the dev-branch. Another issue is that the Android support library in the central maven repository is only r7. Solve this by adding r13 from HoloEverywhere to your local maven repo. Doing this allowed me to successfully build HoloEverywhere libraries and addons which I then used to run both the demo app and some of my own projects using Gradle. I'll create a fork later today with needed build scripts setup if anyone else is interested.

**Comment by HenriqueRocha** [comment]
Great! That would be awesome!

**Comment by Dahlgren** [comment]
Fork is up at https://github.com/Dahlgren/HoloEverywhere/tree/gradle

Since ABS and Android support library is not available from public mirrors I've added a local maven repo with them inside the project folder.

Let me know if you need any more help!

**Comment by HenriqueRocha** [comment]
With some trouble I was able to build the project but it doesn't run.
It doesn't find the MainActivity inside the apk and Studio stopped launching the app after deploying.
I'll just delete everything, uninstall Studio and start over once I have more time.
Thanks anyway for your help.

**Comment by jjalonso** [comment]
I need to use HoloEveryWhere in Android Studio 2... Any new about this?
