### ISSUE TITLE
Problems installing libray

### ISSUE THREAD

**Issue by dementhius** [Prototik/HoloEverywhere#514]
First of all, thanks for your work, I see it working and it looks fine.

I try to install into my project but I´´m having problems importing to Eclipse; I folow the paths you put in the guide, importing from git, deleting from contrib.. and adding the new libray. But when I finish doing all the paths I still have problems in POM.xml,. The trouble is that I have the support-v4-r13.jar there, holoeverywhere recognizes it, but problems is still there.

I dont know if it will be a problems with another librarys I have added before. like original ABS (not the one you add in your library) and SlidingMenu library. 

Is it possible to create a .jar with holoeverywhere and add to projects or could you help me with what I´m wrong?

Thx for your time

P.D.: If you need, I can add some screens.

**Comment by OS-Chris** [comment]
You can't include android libraries as JAR files, they must be imported as an Eclipse project and linked to your project through the Android tab on the properties of your project.

I had drama's setting it up initially as well. Turns out another library I used was using a different support library so my project ended up with 2 versions and spazzed out. What I did was replace all support-xxxxx.jar libraries with the r13 one, refreshed and rebuilt all projects and no more errors.
