### ISSUE TITLE
TabSwipeActivity isn't working on version 1.6.8

### ISSUE THREAD

**Issue by rafaeltoledo** [Prototik/HoloEverywhere#569]
After upgraded to 1.6.8 version, my TabSwipeActivity isn't working anymore. The screen only shows a empty Activity.

**Comment by Prototik** [comment]
More details, please. Code. Or something else. Also checkout new version of library in `abc` branch and report (and reopen this issue) if something wrong.

**Comment by davidp3** [comment]
I just found this bug as I was going to enter one of my own.  I have not yet checked the 'abc' branch... I've been trying to build 'master', which is currently fubar (as you mentioned in another bug related to this).  I will check 'abc'.

The OP is correct.  The problem appears to be related to bug #469.  Apparently, TabSwipeActivity was fixed on Jun 13th and then broken again by a Jun 17th checkin that introduced the AddonTabber stuff.  This appears in the latest release.  The TabSwipeActivity in that version never calls onHandleTabs().  It doesn't help to move the addTab() calls from onHandleTabs() to, say, onCreate, because this produces an error about not being able to add the addon after the Activity was init-ed.  So the window is blank (no tab bar or tab fragments).

**Comment by davidp3** [comment]
Update: The abc branch seems to have been abandoned...

**Comment by davidp3** [comment]
OK, I've got a super-cheap workaround for anyone who had the same issue.  The deal is that AddonTabber is not constructed before onCreate(), as the framework seems to expect.  But you can get there without touching the HoloEverywhere code.  Just create a (parameterless) constructor for your TabSwipeActivity subclass (or your TabSwipeFragment subclass... although I don't know if that one is broken).  In the constructor, call:
`addonTabber()`.  That's it!  This will register the class and then your tabs will appear.

**Comment by rafaeltoledo** [comment]
That's great, David! I suggest you to do a pull request and add this code to the codebase of the library. Thank you :+1:

**Comment by davidp3** [comment]
I'd do that but I can't get trunk to build (not in Eclipse or on command line).  The code has moved on (a lot) from the latest release so I don't even know if the issue is still there.  I'll set up a pull request once I can build and test it.
