### ISSUE TITLE
How to use HoloEverywhere with ActionBarSherlock

### ISSUE THREAD

**Issue by skyflyer** [Prototik/HoloEverywhere#650]
Currently (tested with master branches of both, HoloEverywhere and ABS), there is an overlap in defined attributes between HoloEverywhere and ActionBarSherlock. Eclipse barfs on it, below is just a sample project. Is there a workaround or suggested guidance on how to wire HoloEverywhere with ActionBarSherlock?

First 5 errors:

```
HoloEverywhere/library/res/values/abc_attrs.xml:32: error: Attribute "windowActionBar" has already been defined
HoloEverywhere/library/res/values/abc_attrs.xml:33: error: Attribute "windowActionBarOverlay" has already been defined
HoloEverywhere/library/res/values/abc_attrs.xml:34: error: Attribute "windowSplitActionBar" has already been defined
HoloEverywhere/library/res/values/abc_attrs.xml:45: error: Attribute "actionBarTabStyle" has already been defined
HoloEverywhere/library/res/values/abc_attrs.xml:46: error: Attribute "actionBarTabBarStyle" has already been defined
```

Those attributes are defined in ActionBarSherlock (`ActionBarSherlock/actionbarsherlock/res/values/abs__attrs.xml`) and in HoloEverywhere (`HoloEverywhere/library/res/values/abc_attrs.xml`).

**Comment by BraisGabin** [comment]
Use v1.6.8

**Comment by skyflyer** [comment]
True. After updating ABS with the latest android support library, it compiles and works. Thanks!

**Comment by tomerav0** [comment]
Hi i still got the problem.
I think its because of SDK and ADT updates.

I downloaded the newest master branches of holoeverywhere and ABS.

Also updated my support library from your master branch at ABS libs. According to skyflye is there other source to the support library?

HoloEverywhere-master\library\res\values\abc_attrs.xml:33: error: Attribute "windowActionBarOverlay" has already been defined
HoloEverywhere-master\library\res\values\abc_attrs.xml:34: error: Attribute "windowSplitActionBar" has already been defined
HoloEverywhere-master\library\res\values\abc_attrs.xml:45: error: Attribute "actionBarTabStyle" has already been defined
HoloEverywhere-master\library\res\values\abc_attrs.xml:46: error: Attribute "actionBarTabBarStyle" has already been defined
HoloEverywhere-master\library\res\values\abc_attrs.xml:47: error: Attribute "actionBarTabTextStyle" has already been defined
HoloEverywhere-master\library\res\values\abc_attrs.xml:48: error: Attribute "actionOverflowButtonStyle" has already been defined

**Comment by skyflyer** [comment]
@tigoApp, as @BraisGabin mentioned, you _have_ to use v1.6.8 of HoloEverywhere with ABS in order to get it to work.

**Comment by tomerav0** [comment]
@skyflyer v1.6.8 of HoloEverywhere is the vesrion on the master branch? How can i know which version i have?

**Comment by skyflyer** [comment]
@tigoApp, if you're clonning the HoloEverywhere repository, just issue `git co v1.6.8` locally. If you want to download tag v1.6.8 use this [link](https://github.com/Prototik/HoloEverywhere/archive/v1.6.8.zip).

**Comment by huteri** [comment]
I have been using v1.6.8 but It does not solve the issue.

**Comment by BraisGabin** [comment]
Are you following [this steps](https://github.com/Prototik/HoloEverywhere/wiki/Import-in-IDE/edf4b3e2e451cbec85d214b3ca3e0d6607770ed8)?

**Comment by zenyagami** [comment]
i had this issue as well the latest version on github isnt working, however, using the zip file its working wit ABS again so why? anyone? Thanks

**Comment by Slim1991** [comment]
I found v1.6.8 in here: https://github.com/Prototik/HoloEverywhere/releases/tag/v1.6.8
Is it correct?
It's a Maven project. So, I don't know how to fix the error in pom.xml.

**Comment by snowdream** [comment]
Ok,Thank you!
